/** @type {Object.<string, string>} */
export const escape_word_map = {
	"sum": "Σ​", // has a U+200 zero with character at end, so it is considered different by the parser
	"sumb": "Σ",
	"prod": "∏​", // U+200
    "prodb": "∏",
	"union": "∪",
	"cup": "∪​", // U+200
	"bigcup": "∪",
	"intersect": "∩",
	"cap": "∩​", // U+200
	"bigcap": "∩",
	"alpha": "α",
	"a": "α",
	"beta": "β",
	"b": "β",
	"gamma": "γ",
	"g": "γ",
	"delta": "δ",
	"d": "δ",
	"epsilon": "ε",
	"e": "ε",
	"zeta": "ζ",
	"z": "ζ",
	"eta": "η",
	"h": "η",
	"theta": "θ",
	"th": "θ",
	"iota": "ι",
	"i": "ι",
	"kappa": "κ",
	"k": "κ",
	"lambda": "λ",
	"l": "λ",
	"mu": "μ",
	"m": "μ",
	"nu": "ν",
	"n": "ν",
	"xi": "ξ",
	"x": "ξ",
	"omicron": "ο",
	"o": "ο",
	"pi": "π",
	"p": "π",
	"rho": "ρ",
	"r": "ρ",
	"sigma": "σ",
	"s": "σ",
	"tau": "τ",
	"t": "τ",
	"upsilon": "υ",
	"u": "υ",
	"phi": "φ",
	"f": "φ",
	"chi": "χ",
	"c": "χ",
	"psi": "ψ",
	"ps": "ψ",
	"omega": "ω",
	// Capitals
	"Alpha": "Α",
	"A": "Α",
	"Beta": "Β",
	"B": "Β",
	"Gamma": "Γ",
	"G": "Γ",
	"Delta": "Δ",
	"D": "Δ",
	"Epsilon": "Ε",
	"E": "Ε",
	"Zeta": "Ζ",
	"Z": "Ζ",
	"Eta": "Η",
	"H": "Η",
	"Theta": "Θ",
	"Th": "Θ",
	"Iota": "Ι",
	"I": "Ι",
	"Kappa": "Κ",
	"K": "Κ",
	"Lambda": "Λ",
	"L": "Λ",
	"Mu": "Μ",
	"M": "Μ",
	"Nu": "Ν",
	"N": "Ν",
	"Xi": "Ξ",
	"X": "Ξ",
	"Omicron": "Ο",
	"O": "Ο",
	"Pi": "Π",
	"P": "Π",
	"Rho": "Ρ",
	"R": "Ρ",
	"Sigma": "Σ",
	"S": "Σ",
	"Tau": "Τ",
	"T": "Τ",
	"Upsilon": "Υ",
	"U": "Υ",
	"Phi": "Φ",
	"F": "Φ",
	"Chi": "Χ",
	"C": "Χ",
	"Psi": "Ψ",
	"Ps": "Ψ",
	"Omega": "Ω",

	// Maths
	"eq": "=",
	"equal": "=",
	"equals": "=",
	"lt": "&lt;", // As html doesn't rly like using <> freely
	"leq": "≤",
	"gt": "&gt;",
	"geq": "≥",
	"neq": "≠",
	"times": "×",
	"div": "÷",
	"pm": "±",
	"mp": "∓",
	"cdot": "⋅",
	"to": "→",
	"infty": "∞",
	"approx": "≈",
	"cong": "≅",
	"equiv": "≡",
	"sim": "∼",
	"simeq": "≃",
	"nequiv": "≢",
	"ncong": "≇",
	"nsim": "≁",
	"nsimeq": "≄",
	"napprox": "≉",
	"cross": "×", // Same as times, added it for myself

	"prop": "∝",
	"propto": "∝",
	"in": "∈",
	"notin": "∉",
	"subset": "⊂",
	"subseteq": "⊆",
	"subsetneq": "⊊",
	"supset": "⊃",
	"supseteq": "⊇",
	"supsetneq": "⊋",

	"int": "∫​",
    "intb": "∫",
	"iint": "∬",
	"iiint": "∭",
	"oint": "∮",
	"sqrt": "√",

	// Arrows
	"leftarrow": "←",
	"rightarrow": "→",
	"uparrow": "↑",
	"downarrow": "↓",
	"leftrightarrow": "↔",
	"rightleftarrows": "⇌",
	"mapsto": "↦",
	"equivalent": "⇔",
	"implies": "⇒",
	"iff": "⇔",
	"Leftarrow": "⇐",
	"Rightarrow": "⇒",
	"Uparrow": "⇑",
	"Downarrow": "⇓",
	"LeftRightarrow": "⇔",
	"Longrightarrow": "⟶",
	"Longleftarrow": "⟵",
	"Longleftrightarrow": "⟷",
	"Longmapsto": "⟼",
	"LongLeftarrow": "⟸",
	"LongRightarrow": "⟹",
	"LongEquiv": "⟺",
	"rightsquigarrow" : "⇝",
	"leftsquigarrow" : "⇜",
	"leftrightsquigarrow" : "↭",

	// Arrows incoming
	// Negated / basic extras
    "nleftarrow" : "↚",
    "nrightarrow" : "↛",
    "nleftrightarrow" : "↮",
    "nLeftarrow" : "⇍",
    "nRightarrow" : "⇏",
    "nLeftrightarrow" : "⇎",
    "Leftrightarrow" : "⇔",
    "updownarrow" : "↕",
    "Updownarrow" : "⇕",

    // Diagonal
    "nwarrow" : "↖",
    "nearrow" : "↗",
    "searrow" : "↘",
    "swarrow" : "↙",
    "Nwarrow" : "⇖",
    "Nearrow" : "⇗",
    "Searrow" : "⇘",
    "Swarrow" : "⇙",

    // Maps
    "mapsfrom" : "↤",
    "mapsup" : "↥",
    "mapsdown" : "↧",
    "Mapsfrom" : "⤆",
    "Mapsto" : "⤇",
    "longmapsto" : "⟼",
    "longmapsfrom" : "⟻",
    "Longmapsfrom" : "⟽",
    "twoheadmapsto" : "⤅",
    "twoheadmapsfrom" : "⬶",

    // Long
    "longleftarrow" : "⟵",
    "longrightarrow" : "⟶",
    "longleftrightarrow" : "⟷",
    "longrightsquigarrow" : "⟿",
    "longleftsquigarrow" : "⬳",

    // Multiple / paired arrows
    "Lleftarrow" : "⇚",
    "Rrightarrow" : "⇛",
    "upuparrows" : "⇈",
    "downdownarrows" : "⇊",
    "leftleftarrows" : "⇇",
    "rightrightarrows" : "⇉",
    "leftrightarrows" : "⇆",
    "rightleftarrow" : "⇄",
    "updownarrows" : "⇅",
    "downuparrows" : "⇵",
    "uparrowdownarrow" : "⇅",
    "downarrowuparrow" : "⇵",
    "rightthreearrows" : "⇶",
    "leftthreearrows" : "⬱",
    "rightarrowshortleftarrow" : "⥂",
    "leftarrowshortrightarrow" : "⥃",
    "shortrightarrowleftarrow" : "⥄",
    "barleftarrowrightarrowba" : "↹",

    // Tails, hooks, loops, curved
    "leftarrowtail" : "↢",
    "rightarrowtail" : "↣",
    "looparrowleft" : "↫",
    "looparrowright" : "↬",
    "hookleftarrow" : "↩",
    "hookrightarrow" : "↪",
    "curvearrowleft" : "↶",
    "curvearrowright" : "↷",
    "circlearrowleft" : "↺",
    "circlearrowright" : "↻",
    "acwopencirclearrow" : "↺",
    "cwopencirclearrow" : "↻",
    "Lsh" : "↰",
    "Rsh" : "↱",
    "ldsh" : "↲",
    "rdsh" : "↳",
    "carriagereturn" : "↵",
    "barovernorthwestarrow" : "↸",
    "downzigzagarrow" : "↯",
    "leftwavearrow" : "↜",
    "rightwavearrow" : "↝",
    "updownarrowbar" : "↨",

    // Two-headed
    "twoheadleftarrow" : "↞",
    "twoheaduparrow" : "↟",
    "twoheadrightarrow" : "↠",
    "twoheaddownarrow" : "↡",
    "twoheadrightarrowtail" : "⤖",
    "twoheadleftarrowtail" : "⬻",
    "twoheadleftdbkarrow" : "⬷",

    // Dashed, white, bar
    "leftdasharrow" : "⇠",
    "updasharrow" : "⇡",
    "rightdasharrow" : "⇢",
    "downdasharrow" : "⇣",
    "dashleftarrow" : "⇠",
    "dashrightarrow" : "⇢",
    "barleftarrow" : "⇤",
    "rightarrowbar" : "⇥",
    "leftwhitearrow" : "⇦",
    "upwhitearrow" : "⇧",
    "rightwhitearrow" : "⇨",
    "downwhitearrow" : "⇩",
    "whitearrowupfrombar" : "⇪",
    "circleonrightarrow" : "⇴",
    "rightarrowtriangle" : "⇾",
    "leftarrowtriangle" : "⇽",
    "leftrightarrowtriangle" : "⇿",
    "nvleftarrow" : "⇷",
    "nvrightarrow" : "⇸",
    "nvleftrightarrow" : "⇹",
    "nVleftarrow" : "⇺",
    "nVrightarrow" : "⇻",
    "nVleftrightarrow" : "⇼",
    "nvLeftarrow" : "⤂",
    "nvRightarrow" : "⤃",
    "nvLeftrightarrow" : "⤄",

    // Harpoons
    "leftharpoonup" : "↼",
    "leftharpoondown" : "↽",
    "upharpoonright" : "↾",
    "upharpoonleft" : "↿",
    "rightharpoonup" : "⇀",
    "rightharpoondown" : "⇁",
    "downharpoonright" : "⇂",
    "downharpoonleft" : "⇃",
    "leftrightharpoons" : "⇋",
    "rightleftharpoons" : "⇌",
    "leftrightharpoonupdown" : "⥊",
    "leftrightharpoondownup" : "⥋",
    "updownharpoonrightleft" : "⥌",
    "updownharpoonleftright" : "⥍",
    "leftrightharpoonupup" : "⥎",
    "updownharpoonrightright" : "⥏",
    "leftrightharpoondowndown" : "⥐",
    "updownharpoonleftleft" : "⥑",
    "barleftharpoonup" : "⥒",
    "rightharpoonupbar" : "⥓",
    "barupharpoonright" : "⥔",
    "downharpoonrightbar" : "⥕",
    "barleftharpoondown" : "⥖",
    "rightharpoondownbar" : "⥗",
    "barupharpoonleft" : "⥘",
    "downharpoonleftbar" : "⥙",
    "leftharpoonupbar" : "⥚",
    "barrightharpoonup" : "⥛",
    "upharpoonrightbar" : "⥜",
    "bardownharpoonright" : "⥝",
    "leftharpoondownbar" : "⥞",
    "barrightharpoondown" : "⥟",
    "upharpoonleftbar" : "⥠",
    "bardownharpoonleft" : "⥡",
    "leftleftharpoons" : "⥢",
    "upharpoonsleftright" : "⥣",
    "rightrightharpoons" : "⥤",
    "downharpoonsleftright" : "⥥",
    "leftrightharpoonsup" : "⥦",
    "leftrightharpoonsdown" : "⥧",
    "rightleftharpoonsup" : "⥨",
    "rightleftharpoonsdown" : "⥩",
    "leftharpoonupdash" : "⥪",
    "dashleftharpoondown" : "⥫",
    "rightharpoonupdash" : "⥬",
    "dashrightharpoondown" : "⥭",
    "updownharpoonsleftright" : "⥮",
    "downupharpoonsleftright" : "⥯",
    "upequilibrium" : "⥮",
    "uprevequilibrium" : "⥯",

    // Tailed / barred / dotted variants
    "nvrightarrowtail" : "⤔",
    "nVrightarrowtail" : "⤕",
    "nvtwoheadrightarrow" : "⤀",
    "nVtwoheadrightarrow" : "⤁",
    "nvtwoheadrightarrowtail" : "⤗",
    "nVtwoheadrightarrowtail" : "⤘",
    "nvtwoheadleftarrow" : "⬴",
    "nVtwoheadleftarrow" : "⬵",
    "nvleftarrowtail" : "⬹",
    "nVleftarrowtail" : "⬺",
    "nvtwoheadleftarrowtail" : "⬼",
    "nVtwoheadleftarrowtail" : "⬽",
    "leftdotarrow" : "⬸",
    "rightdotarrow" : "⤑",
    "leftbkarrow" : "⤌",
    "rightbkarrow" : "⤍",
    "leftdbkarrow" : "⤎",
    "rightdbkarrow" : "⤏",
    "drbkarrow" : "⤐",
    "uparrowbarred" : "⤉",
    "downarrowbarred" : "⤈",
    "baruparrow" : "⤒",
    "downarrowbar" : "⤓",
    "leftdbltail" : "⤛",
    "rightdbltail" : "⤜",
    "diamondleftarrow" : "⤝",
    "rightarrowdiamond" : "⤞",
    "diamondleftarrowbar" : "⤟",
    "barrightarrowdiamond" : "⤠",
    "leftquaddarrow" : "⭅",
    "rightquaddarrow" : "⭆",

    // Curved arrows
    "rightcurvedarrow" : "⤳",
    "uprightcurvearrow" : "⤴",
    "downrightcurvedarrow" : "⤵",
    "leftdowncurvedarrow" : "⤶",
    "rightdowncurvedarrow" : "⤷",
    "cwrightarcarrow" : "⤸",
    "acwleftarcarrow" : "⤹",
    "acwoverarcarrow" : "⤺",
    "acwunderarcarrow" : "⤻",
    "curvearrowrightminus" : "⤼",
    "curvearrowleftplus" : "⤽",
    "cwundercurvearrow" : "⤾",
    "ccwundercurvearrow" : "⤿",
    "leftcurvedarrow" : "⬿",
    "fdiagovnearrow" : "⤯",
    "rdiagovsearrow" : "⤰",

    // Circle arrows
    "acwgapcirclearrow" : "⟲",
    "cwgapcirclearrow" : "⟳",
    "acwcirclearrow" : "⥀",
    "cwcirclearrow" : "⥁",
    "leftrightarrowcircle" : "⥈",
    "twoheaduparrowcircle" : "⥉",
    "rightarrowonoplus" : "⟴",
    "leftarrowonoplus" : "⬲",
    "circleonleftarrow" : "⬰",
    "uparrowoncircle" : "⦽",
    "circledownarrow" : "⧬",
    "blackcircledownarrow" : "⧭",
    "blackdiamonddownarrow" : "⧪",
    "rangledownzigzagarrow" : "⍼",

    // Arrows combined with other symbols
    "rightarrowplus" : "⥅",
    "leftarrowplus" : "⥆",
    "similarrightarrow" : "⥲",
    "leftarrowsimilar" : "⥳",
    "rightarrowsimilar" : "⥴",
    "rightarrowapprox" : "⥵",
    "leftarrowless" : "⥷",
    "leftarrowsubset" : "⥺",
    "equalrightarrow" : "⥱",
    "equalleftarrow" : "⭀",
    "bsimilarleftarrow" : "⭁",
    "leftarrowbackapprox" : "⭂",
    "rightarrowgtr" : "⭃",
    "rightarrowsupset" : "⭄",
    "bsimilarrightarrow" : "⭇",
    "rightarrowbackapprox" : "⭈",
    "similarleftarrow" : "⭉",
    "leftarrowapprox" : "⭊",
    "leftarrowbsimilar" : "⭋",
    "rightarrowbsimilar" : "⭌",
    "draftingarrow" : "➛",

    // Combining arrows (accents)
    "overleftarrow" : "⃖",
    "overrightarrow" : "⃗",
    "overleftrightarrow" : "⃡",
    "leftharpoonaccent" : "⃐",
    "rightharpoonaccent" : "⃑",
    "underrightharpoondown" : "⃬",
    "underleftharpoondown" : "⃭",
    "underleftarrow" : "⃮",
    "underrightarrow" : "⃯",

    // More from data.py
    "leftrightharpoondown" : "⥐",
    "rightharpoonsupdown" : "⥤",
    "upharpoonrightdown" : "⇂",
    "leftrightharpoonup" : "⥎",
    "rightupdownharpoon" : "⥏",
    "leftharpoonsupdown" : "⥢",
    "upharpoonleftdown" : "⇃",
    "leftupdownharpoon" : "⥑",
    "upharpoonrightup" : "↾",
    "leftrightharpoon" : "⥊",
    "rightleftharpoon" : "⥋",
    "downdownharpoons" : "⥥",
    "upharpoonleftup" : "↿",
    "rightbarharpoon" : "⥬",
    "barrightharpoon" : "⥭",
    "revequilibrium" : "⇋",
    "longmappedfrom" : "⟻",
    "Longmappedfrom" : "⟽",
    "leftbarharpoon" : "⥪",
    "barleftharpoon" : "⥫",
    "updownharpoons" : "⥮",
    "downupharpoons" : "⥯",
    "RightArrowBar" : "⇥",
    "LeftArrowBar" : "⇤",
    "DownArrowBar" : "⤓",
    "upupharpoons" : "⥣",
    "equilibrium" : "⇌",
    "nHdownarrow" : "⇟",
    "seovnearrow" : "⤭",
    "neovsearrow" : "⤮",
    "neovnwarrow" : "⤱",
    "nwovnearrow" : "⤲",
    "rightarrowx" : "⥇",
    "RRightarrow" : "⭆",
    "mappedfrom" : "↤",
    "DDownarrow" : "⟱",
    "Mappedfrom" : "⤆",
    "Ddownarrow" : "⤋",
    "UpArrowBar" : "⤒",
    "rightimply" : "⥰",
    "leftarrowx" : "⬾",
    "LLeftarrow" : "⭅",
    "lightning" : "↯",
    "Lightning" : "↯",
    "nHuparrow" : "⇞",
    "dasharrow" : "⇢",
    "impliedby" : "⟸",
    "righttail" : "⤚",
    "nwsearrow" : "⤡",
    "neswarrow" : "⤢",
    "hknwarrow" : "⤣",
    "hknearrow" : "⤤",
    "linefeed" : "↴",
    "UUparrow" : "⟰",
    "Uuparrow" : "⤊",
    "drbkarow" : "⤐",
    "lefttail" : "⤙",
    "hksearow" : "⤥",
    "hkswarow" : "⤦",
    "dbkarow" : "⤏",
    "leadsto" : "⤳",
    "subrarr" : "⥹",
    "suplarr" : "⥻",
    "ltlarr" : "⥶",
    "gtrarr" : "⥸",
    "gets" : "←",
    "dlsh" : "↲",
    "Ldsh" : "↲",
    "drsh" : "↳",
    "Rdsh" : "↳",

    // CamelCase vector aliases
    "RightDownVectorBar" : "⥕",
    "DownRightVectorBar" : "⥗",
    "RightDownTeeVector" : "⥝",
    "DownRightTeeVector" : "⥟",
    "DownLeftVectorBar" : "⥖",
    "LeftDownVectorBar" : "⥙",
    "DownLeftTeeVector" : "⥞",
    "LeftDownTeeVector" : "⥡",
    "RightUpVectorBar" : "⥔",
    "RightUpTeeVector" : "⥜",
    "LeftUpVectorBar" : "⥘",
    "LeftUpTeeVector" : "⥠",
    "RightVectorBar" : "⥓",
    "RightTeeVector" : "⥛",
    "LeftVectorBar" : "⥒",
    "LeftTeeVector" : "⥚",

    // Maps (extra)
    "MapsDown" : "↧",
    "MapsUp" : "↥",




	"^": "^", // Like printing the characters, not actually using them
	"_": "_",
	"\\": "\\",
	"forall": "∀",
	"exists": "∃",
	"therefore": "∴",
	"because": "∵",
	"since" : "∵",
	"lfloor": "⌊",
	"rfloor": "⌋",
	"lceil": "⌈",
	"rceil": "⌉",
	"langle": "⟨",
	"rangle": "⟩",
};

export let escape_word_list = Object.keys(escape_word_map).sort((a, b) => b.length - a.length);

// This is for functions, which don't also have an explicit symbol
escape_word_list.push(...[
	"over", // So \over{a}{b} means put b above a
	"under",
	"cancel", // \cancel{} Makes a diagonal strikethrough the character/expression, like in ≠
	"cancelangle", // \cancel{angle}{stuff}, angle in degrees.
	"canceldir", // \cancel{dir}{stuff} Cancels in specified directions: trbl (top right bottom left), tlbr (top left bottom right), ud (up to down), lr (left to right)
	"frac", // \frac{a}{b} is explicitly division, so a above b with a horizontal line between
	"atop", // \atop{a}{b} is like frac, but without the horizontal line
	"root",
	"attach", // \attach{}{}{}{}{}{}{}
	"attacho", // Like attach, but also additional parameter of overlap
    "attachos", // Like attacho, but also option to configure how much smaller the super and subscript go (default = 0.6 on the above)
	// Question, how do i do multi line braces?
	// Latex does it with \left and \right, so can prob do that.
	"left", // \left {(}{....}, the first input is what kind of bracket, the other is the content it is scaled with
	"right", // same iea
	"lr", // \lr{ab}{content} -> becomes a{content}b, where a and b scale with the content. By default, if multiple characters, itll use first character for a, and rest for b.
	"left[",
	"right]",
	"left(",
	"right)",
	"left{",
	"right}",
	"left|",
	"right|",
	"lr(",
	"lr[",
	"lr{",
	"lr|",


	// to make matrix, \left {[}{\right{]}{..tablesomehow...}} // so these should not scale stuff
	// if want to use curly braces, must backslash them, so \left{\{}{....}
	// these can be multilined as they will scale with the content, should be able to make similar to sqrt

    "scale", // scaling the element by some scale
    "scalew",
    "scaleh",
    "rotate", // works in degrees

	"mathbb", // {R a b} -> ℝ 𝕒 𝕓
	"mathcal", // {R a b} -> ℛ 𝒶 b

	"underline",
	"overline"
])
// The idea will be to keep scanning forward, till only one of them satisfies
// If none match, then just print the \ as normal
// If multiple match at one point and then none match, then i want the longest ones, sorted it

// Refers to functions, which pop the next argument behind them.
export let single_pop_list = ["sqrt", "cancel", "mathbb", "mathcal", "underline", "overline", "left[", "right]", "left(", "right)", "left{", "right}", "left|", "right|", "lr(", "lr[", "lr{", "lr|"]; 
export let double_pop_list = ["over","under","frac","atop","root","left","right","scale","scalew","scaleh","rotate","cancelangle", "canceldir", "lr"]; // These pop the next two arguments behind them, and use them in some way. For example, \frac{a}{b} will pop a and b, and make a fraction with them
export let custom_handling_list = ["attach", "attacho", "attachos"]; // For sqrt, i want it to be usable as a character and a function. SO if sqrt is followed by a string, tis character, if followed by a div, its function

export let updown_modifier = ["Σ", "∏", "∪", "∩", "∫", "∬", "∭", "∮"]

/** @type {Object.<string, string>} */
export let mathbb_map = {
	"a": "𝕒",
	"b": "𝕓",
	"c": "𝕔",
	"d": "𝕕",
	"e": "𝕖",
	"f": "𝕗",
	"g": "𝕘",
	"h": "𝕙",
	"i": "𝕚",
	"j": "𝕛",
	"k": "𝕜",
	"l": "𝕝",
	"m": "𝕞",
	"n": "𝕟",
	"o": "𝕠",
	"p": "𝕡",
	"q": "𝕢",
	"r": "𝕣",
	"s": "𝕤",
	"t": "𝕥",
	"u": "𝕦",
	"v": "𝕧",
	"w": "𝕨",
	"x": "𝕩",
	"y": "𝕪",
	"z": "𝕫",
	"A": "𝔸",
	"B": "𝔹",
	"C": "ℂ",
	"D": "𝔻",
	"E": "𝔼",
	"F": "𝔽",
	"G": "𝔾",
	"H": "ℍ",
	"I": "𝕀",
	"J": "𝕁",
	"K": "𝕂",
	"L": "𝕃",
	"M": "𝕄",
	"N": "ℕ",
	"O": "𝕆",
	"P": "ℙ",
	"Q": "ℚ",
	"R": "ℝ",
	"S": "𝕊",
	"T": "𝕋",
	"U": "𝕌",
	"V": "𝕍",
	"W": "𝕎",
	"X": "𝕏",
	"Y": "𝕐",
	"Z": "ℤ",
	"0": "𝟘",
	"1": "𝟙",
	"2": "𝟚",
	"3": "𝟛",
	"4": "𝟜",
	"5": "𝟝",
	"6": "𝟞",
	"7": "𝟟",
	"8": "𝟠",
	"9": "𝟡",
}

/** @type {Object.<string, string>} */
export let mathcal_map = {
	"a": "𝒶",
	"b": "𝒷",
	"c": "𝒸",
	"d": "𝒹",
	"e": "ℯ",
	"f": "𝒻",
	"g": "ℊ",
	"h": "𝒽",
	"i": "𝒾",
	"j": "𝒿",
	"k": "𝓀",
	"l": "𝓁",
	"m": "𝓂",
	"n": "𝓃",
	"o": "ℴ",
	"p": "𝓅",
	"q": "𝓆",
	"r": "𝓇",
	"s": "𝓈",
	"t": "𝓉",
	"u": "𝓊",
	"v": "𝓋",
	"w": "𝓌",
	"x": "𝓍",
	"y": "𝓎",
	"z": "𝓏",
	"A": "𝒜",
	"B": "ℬ",
	"C": "𝒞",
	"D": "𝒟",
	"E": "ℰ",
	"F": "ℱ",
	"G": "𝒢",
	"H": "ℋ",
	"I": "ℐ",
	"J": "𝒥",
	"K": "𝒦",
	"L": "ℒ",
	"M": "ℳ",
	"N": "𝒩",
	"O": "𝒪",
	"P": "𝒫",
	"Q": "𝒬",
	"R": "ℛ",
	"S": "𝒮",
	"T": "𝒯",
	"U": "𝒰",
	"V": "𝒱",
	"W": "𝒲",
	"X": "𝒳",
	"Y": "𝒴",
	"Z": "𝒵"
}